sudo: required

language: python

services:
- docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_script:
- export DOCKER_REPO=pocketsquare/pocket-square-present
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: myvXvV8zZl7peDTV29qZqqdQcZ+A06sjUpNnC2TJMxcTc8GfS4QMEOT1Jq0LF110Lo8HajTz8LTe6nyCNNQ5LyM5Dnxob42GVbhmkOuyJ00OnUiZIqDb+BekBAEwdq2/4nRkU8aNKiWIvm63OGteopwo7wI8i0xDPCqXxXDhYnYJ6E4A0Df8MZ5+/YKBrZCaHpsQRHkk8gcfoxTWNhB+pFWyyBnCfFax8WKQYytFNrt/wE7lgzPZ1qjiYwJtB+rnwtLW77IppAvj53pSJBw+Qyxkm6n8M4bAd2Npot87mUD/0Mt3/9WYwit03SkF3RkyaeE8Q8UWouY3t7P87SzgoLwQ6XkA1hovcS0s1UDPyi5yFoSBwjCJjqIK6hjpO5sMDTefCZVLQjkSQ1mDHxTCTe8HeN5h2LV3ELw8PGF9AnDKFZ5qSw5YRlH7jkH+HTUSdXS1P07d2zrUmuT6fDt1HpcCVxFjo1N9yWYtHEDcHT03gJBy0UlbtcH6IwNEeihS3/jkNM+q8M+rkEHPuNN+HHmJdhOuB9+EF35RtzmMlNt/9gfHbGIKqu1e3rC5xiwSTG5ZByF8LLWIfu8v8p96MloSWdf2kAoEaWkV6cpU0omOkEMvWh3aX+Zfl0I9V1UIRp6wcvwZ0LlR7sIdufbTC3QTKoJhEgYvCqwKKvEPkBA=
  - secure: YhSgwBNryvNrmqDlZp7rc1r9+vs0BuYaQP9qtRiaicbw14oVPOWHCY7WWu+xrInFRa6pCdrtW44jsp022zr4EYSMiovbABd1tEajB3jldqLNOixZk891n4xGH0wgEA34J/dbNuhu39UNOdTTltBsDMBmaZCGkBga77Dewyi1ZM5uNzMCVNTs1GrjqCQnMSr2v/UuEDNKuOqpGEjoiZlpOGSYXpbgyRLN6ZHMyJn9olgaDAbeGoEmBo6oNJFDhQm8QISaiECs9YOtDUHUCWKYgZBGGtYEwYOGV4nHyQOq8D/fYKuAvvhl2Khkis0l5cYTHMMyVA8Pl3dcm0xpZzQYd2xM5/4Tv8ZnFKlmM7LVPD+DDh6+Odtx3AhYHlgOgwlP4hYKuvrUeKAO4v69sFG/Hjvtn6mgLMvMcl0twsky3z+xl4Uae9PsKRNbCDPU5MPaLkYfBa7IR5ndv2KsXx4cjCweeWUrWH16fqLe9pa6q+jAFrB5RaIjCjmxpHpaN+wlUDWLQJ561yWNlFIJTt7ZInxhX6I6uOycMpS2qep5q93WHO/W3sWTMOeiVIGH+gOo+6UCe5s/dfHu2G3+eLwVSQ9TevInk6fKnyzhdMQxIxuDOa622Qcq+oBRQYdBJyd2hrgsx8QIWtPbgslb9uHb/GjOj3Vl8dhZ6AzEhLJl12s=
  - secure: uxf96eeQPzXFn8OLtInADTwtjbq67b1+yatn59n96g/8il9TOiF26joVhNm5WknAt2drUYKhYadaMGTK0WtB8ezu3A3Dxjq3xXKerDRnjWhCcFjCDbKeVzFcjy0IrqvSEkDb7DEznkmJkdM+69G9sgvVNSA9FU2JOYLhdQ3Uni/HaHUzRxqUbRN05h3UEBWmGPiHNyDQgTBmU8qSZfhKUD3E2lMMaHtvsW7Ienmw5arjK5KIKfAVNFOC5++99RaLLc2VTUa81lYQc8RQtJV3D+qsCyvGngmGp0Xb8nJbu6FtsHfOHGtD3J6Jiq/PF2WHJY9z/tC20kfiy7D6ZfJBY4Q2Z22C89dzgDF6LKeMmS/wbo04H4b9M/dyfs5huxU+Z0UK7ipTvZR7cT6Civ16qJpFUtzBemZ1GHRifMb7Qjvx5ziWDHfdFIJgg7Mi6snvbImLr8I9TIBTMfUADecU1tHwvkNpfCbWxZorsVbRxlxDhweBP04O8vhoNo7Cqkq+1P1+fQdQ8m7QDTwmot0dA7SOfkqYDDtnG5FJ8t944wQP32i8kVnXTOC0/UjLSqcFmErl8c8cXfoTL09kVF7mQkXeeTWSSlOkHQK41/bXdeCbuJcyfM32oENsj1IlrceSfX5cb+2eEMcyUohT6ZLktz8EPcSLQrfnh3EQTi8SJA0=
